//MYSQL
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) values('${upperCaseName}_MGR','${desc}管理',1,2,'/${lowerCaseName}/${requestPath}.action',0,100);
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select 'ADD_${upperCaseName}','添加',2,permission_id,'/${lowerCaseName}/${requestPath}!input.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select 'UPDATE_${upperCaseName}','修改',2,permission_id,'/${lowerCaseName}/${requestPath}!input.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select 'QUERY_${upperCaseName}','查询',2,permission_id,'/${lowerCaseName}/${requestPath}!listAjax.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select 'SAVE_${upperCaseName}','保存',2,permission_id,'/${lowerCaseName}/${requestPath}!saveByOperate.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select 'BATCH_DELETE_${upperCaseName}','删除',2,permission_id,'/${lowerCaseName}/${requestPath}!delete.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';

//ORACLE
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) values(S_T_SYS_PERMISSION.NEXTVAL,'${upperCaseName}_MGR','${desc}管理',1,2,'/${lowerCaseName}/${requestPath}.action',0,100);
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select S_T_SYS_PERMISSION.NEXTVAL,'ADD_${upperCaseName}','添加',2,permission_id,'/${lowerCaseName}/${requestPath}!input.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select S_T_SYS_PERMISSION.NEXTVAL,'UPDATE_${upperCaseName}','修改',2,permission_id,'/${lowerCaseName}/${requestPath}!input.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select S_T_SYS_PERMISSION.NEXTVAL,'QUERY_${upperCaseName}','查询',2,permission_id,'/${lowerCaseName}/${requestPath}!listAjax.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select S_T_SYS_PERMISSION.NEXTVAL,'SAVE_${upperCaseName}','保存',2,permission_id,'/${lowerCaseName}/${requestPath}!saveByOperate.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
insert into t_sys_permission(PERMISSION_ID,PERMISSION_CODE,TITLE,PERMISSION_TYPE,PARENT_ID,URL,DELETABLE,SYSTEM_ID) select S_T_SYS_PERMISSION.NEXTVAL,'BATCH_DELETE_${upperCaseName}','删除',2,permission_id,'/${lowerCaseName}/${requestPath}!delete.action',0,100 from t_sys_permission where PERMISSION_CODE='${upperCaseName}_MGR';
<%@ page contentType="text/html;charset=UTF-8" %>