insert into t_sys_role (ROLE_ID,ROLE_CODE, TITLE, DESCRIPTION, STATUS) values (1,'test1', 'test1', 'test1', 1)
insert into t_sys_role (ROLE_ID,ROLE_CODE, TITLE, DESCRIPTION, STATUS) values (2,'test2', 'test1', 'test1', 1)
insert into t_sys_role (ROLE_ID,ROLE_CODE, TITLE, DESCRIPTION, STATUS) values (3,'test3', 'test1', 'test1', 1)
insert into t_sys_membership (MEMBERSHIP_ID, ROLE_ID, USER_ID) values (1, 1, 1)
insert into t_sys_membership (MEMBERSHIP_ID, ROLE_ID, USER_ID) values (2, 2, 1)
insert into t_sys_membership (MEMBERSHIP_ID, ROLE_ID, USER_ID) values (3, 1, 3)
insert into t_sys_membership (MEMBERSHIP_ID, ROLE_ID, USER_ID) values (4, 2, 3)
insert into t_sys_membership (MEMBERSHIP_ID, ROLE_ID, USER_ID) values (5, 3, 3)
insert into t_sys_users (USER_ID, USER_CODE,AUTHENTICATOR, DEPT_ID, NAME, EMAIL, MOBILE, CREATE_TIME, STATUS) values (1,'user1', 'aaaaaaaaaaa', 1, '123', '123', '123', '123', 1)
insert into t_sys_users (USER_ID, USER_CODE,AUTHENTICATOR, DEPT_ID, NAME, EMAIL, MOBILE, CREATE_TIME, STATUS) values (2,'user2', 'aaaaaaaaaaa', 1, '123', '123', '123', '123', 1)
insert into t_sys_users (USER_ID, USER_CODE,AUTHENTICATOR, DEPT_ID, NAME, EMAIL, MOBILE, CREATE_TIME, STATUS) values (3,'user3', 'aaaaaaaaaaa', 1, '123', '123', '123', '123', 1)
